name: CI/CD for simple-http-checker

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint-static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Display Python version and location
        run: |
          python --version
          which python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Linting and format checks
        run: |
          ruff check .
          black --check .
      - name: Static type checks
        run: |
          mypy src/
      - name: Security checks
        run: |
          bandit -c pyproject.toml -r .
      - name: run check-url
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -e .
          pip install --upgrade pip
          check-urls https://google.com https://foobar.com https://httpbin.org/status/404
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Automated test with Pytest
        run: |
          pytest
  release:
    runs-on: ubuntu-latest
    # needs:
    #   - tests
    #   - lint-static-checks
    # permissions:
    #   contents: write
    #   id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install python-semantic-release
      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          semantic-release publish
      # - name: Build the Python project
      #   run: |
      #     python -m build
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: simple-http-checker=${{ github.sha }}
      #     path: dist/
